[package]
name = "spin-rs"
version = "0.2.0"
edition = "2021"

[dependencies]
hyper-reverse-proxy = "0.5.*"
hyper = { version = "0.14.*", features = ["full"] }
tokio = { version = "1.*", features = ["full"] }

[profile.release]
opt-level = 3
strip = true
debug = false
codegen-units = 1
lto = true
